import {
	type RouteConfig,
	index,
	route,
	layout,
} from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("sign-in", "routes/auth.tsx"),
	route("sign-up", "routes/sign-up.tsx"),
	route("auth/verify", "routes/auth.verify.tsx"),
	route("auth/reset", "routes/auth.reset.tsx"),
	route("auth/mfa", "routes/auth.mfa.tsx"),
	route("auth/google", "routes/auth.google.tsx"),
	route("auth/google/callback", "routes/auth.google.callback.tsx"),
	route("logout", "routes/logout.tsx"),
	route("agent", "routes/api.agent.tsx"),
	route("settings/data", "routes/settings.data.tsx"),
	route("onboarding", "routes/onboarding.tsx"),
	route("onboarding/invite", "routes/onboarding.invite.tsx"),
	route("invite/:token", "routes/invite.$token.tsx"),
	route("org/switch", "routes/org.switch.tsx"),
	layout("routes/dashboard-layout.tsx", [
		route("dashboard", "routes/dashboard.tsx"),
		route("dashboard/assistant", "routes/dashboard.assistant.tsx"),
		route("dashboard/audit", "routes/dashboard.audit.tsx"),
		route("dashboard/organization", "routes/dashboard.organization.tsx"),
		route("dashboard/banking", "routes/dashboard.banking.tsx"),
		route("dashboard/knowledge", "routes/dashboard.knowledge.tsx"),
		route("dashboard/documents", "routes/dashboard.documents.tsx"),
		route("dashboard/memories", "routes/dashboard.memories.tsx"),
		route("dashboard/search", "routes/dashboard.search.tsx"),
		route("dashboard/invoices", "routes/dashboard.invoices.tsx"),
		route("dashboard/recents", "routes/dashboard.recents.tsx"),
		route("dashboard/inventory", "routes/dashboard.inventory.tsx"),
		route("dashboard/inventory/:category", "routes/dashboard.inventory.$category.tsx"),
		route("dashboard/agent-model", "routes/dashboard.agent-model.tsx"),
		route("dashboard/downloads", "routes/dashboard.downloads.tsx"),
		route("dashboard/integrations", "routes/dashboard.integrations.tsx"),
		route(
			"dashboard/integrations/payments",
			"routes/dashboard.integrations.payments.tsx",
		),
		route(
			"dashboard/integrations/:provider",
			"routes/dashboard.integrations.$provider.tsx",
		),
		route("dashboard/settings", "routes/dashboard.settings.tsx"),
		route("dashboard/:section", "routes/dashboard.section.tsx"),
	]),
	route(":slug", "routes/site.$slug.tsx"),
] satisfies RouteConfig;
